name: Test

on:
  push:
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - uses: actions/checkout@v3
      with:
        # Include all history to get tags etc. for versioning
        fetch-depth: 0
    - name: Install Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        channels: conda-forge
        channel-priority: strict
        miniforge-variant: Mambaforge
        use-mamba: true
    - name: Install Nox
      run: mamba install nox
    - name: Install test environments
      run: nox --install-only --verbose
    - name: Run tests
      run: nox --reuse-existing-virtualenvs --no-install
